"""Command-line interface for Ezra agent."""

import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.table import Table

from .companion_client import CompanionClient
from .config import ConfigManager
from .device import DeviceScanner

# Default options to avoid B008 errors
_CONFIG_OPTION = typer.Option(
    None, "--config", "-c", help="Configuration file path",
)

app = typer.Typer(help="Ezra Control CLI - Manage your Ezra agent")
console = Console()


@app.command()
def setup():
    """Interactive setup wizard for Ezra agent."""
    console.print(Panel.fit(
        "[bold cyan]Ezra Device Agent - Setup Wizard[/bold cyan]",
        border_style="cyan",
    ))
    console.print()
    console.print("This wizard will help you configure the Ezra Device Agent.")
    console.print("You will need the URL of your companion server.\n")

    # Get agent directory
    agent_dir = Path.home() / ".ezra"
    env_path = agent_dir / ".env"

    # Check if .env already exists
    if env_path.exists():
        if not Confirm.ask(
            f"\n⚠️  Configuration already exists at {env_path}. Overwrite?",
            default=False,
        ):
            console.print("\n[yellow]Setup cancelled.[/yellow]")
            return

    # Companion Server URL
    console.print("[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Companion Server Configuration[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")
    console.print("\nExamples:")
    console.print("  • Local development: http://localhost:3000")
    console.print("  • Production: https://companion.example.com:8443")
    console.print("  • Self-hosted: https://192.168.1.100:8443\n")

    companion_url = Prompt.ask(
        "Companion server URL",
        default="http://localhost:3000",
    )

    # Test connection
    console.print(f"\n🔍 Testing connection to {companion_url}...")
    
    # Create temporary config to test
    class TempConfig:
        companion_url = companion_url
        timeout = 10000
        max_retries = 3

    try:
        client = CompanionClient(TempConfig())  # type: ignore
        if client.health_check():
            console.print("[green]✅ Connection successful![/green]")
        else:
            console.print("[yellow]⚠️  Could not connect to companion server.[/yellow]")
            if not Confirm.ask("Continue anyway?", default=False):
                console.print("\n[yellow]Setup cancelled.[/yellow]")
                return
    except Exception as e:
        console.print(f"[yellow]⚠️  Connection test failed: {e}[/yellow]")
        if not Confirm.ask("Continue anyway?", default=False):
            console.print("\n[yellow]Setup cancelled.[/yellow]")
            return

    # Policy Public Key
    console.print("\n[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Policy Verification[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")
    console.print("\nPath to the Ed25519 public key for verifying action plans.")
    console.print("This should match the private key used by the companion server.\n")

    policy_pub_key_path = Prompt.ask(
        "Public key path",
        default="/etc/ezra/policy_pub.key",
    )

    # Device Enrollment Token
    console.print("\n[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Device Enrollment (Optional)[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")
    console.print("\nLeave empty if not using enrollment tokens.\n")

    enrollment_token = Prompt.ask(
        "Enrollment token",
        default="",
    )

    # Additional Configuration
    console.print("\n[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Additional Configuration[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")

    device_id = Prompt.ask(
        "\nDevice ID",
        default="ezra_device_001",
    )

    data_dir = Prompt.ask(
        "Data directory",
        default=str(Path.home() / ".ezra" / "data"),
    )

    cache_dir = Prompt.ask(
        "Cache directory",
        default=str(Path.home() / ".ezra" / "cache"),
    )

    backup_dir = Prompt.ask(
        "Backup directory",
        default=str(Path.home() / ".ezra" / "backups"),
    )

    log_level = Prompt.ask(
        "Log level",
        choices=["debug", "info", "warning", "error"],
        default="info",
    )

    # Create .env file
    console.print("\n[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Saving Configuration[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")

    # Ensure agent directory exists
    agent_dir.mkdir(parents=True, exist_ok=True)

    # Create .env content
    env_content = f"""# Ezra Device Agent - Environment Configuration
# Generated by setup wizard on {Path(__file__).name}
# NEVER commit this file to version control!

# ============================================================
# Companion Server Configuration
# ============================================================
COMPANION_BASE_URL={companion_url}

# ============================================================
# Policy Verification
# ============================================================
POLICY_PUB_KEY_PATH={policy_pub_key_path}

# ============================================================
# Device Enrollment
# ============================================================
DEVICE_ENROLLMENT_TOKEN={enrollment_token}

# ============================================================
# Device Configuration
# ============================================================
DEVICE_ID={device_id}
DATA_DIR={data_dir}
CACHE_DIR={cache_dir}
BACKUP_DIR={backup_dir}
LOG_LEVEL={log_level}

# ============================================================
# Security Settings
# ============================================================
VERIFY_SSL=true
REQUEST_TIMEOUT=30
MAX_RETRIES=3
"""

    # Write .env file
    env_path.write_text(env_content)
    env_path.chmod(0o600)

    console.print(f"\n[green]✅ Configuration saved to: {env_path}[/green]")
    console.print("[green]🔒 File permissions set to 600 (owner read/write only)[/green]")

    # Create data directories
    Path(data_dir).mkdir(parents=True, exist_ok=True)
    Path(cache_dir).mkdir(parents=True, exist_ok=True)
    Path(backup_dir).mkdir(parents=True, exist_ok=True)

    console.print(f"\n[green]✅ Created data directories[/green]")

    # Next steps
    console.print("\n[bold]─" * 60 + "[/bold]")
    console.print("[bold cyan]Next Steps[/bold cyan]")
    console.print("[bold]─" * 60 + "[/bold]")
    console.print("\n1. Ensure you have the public key file:")
    console.print(f"   {policy_pub_key_path}")
    console.print("\n2. Test the connection:")
    console.print("   ezractl test")
    console.print("\n3. Scan device information:")
    console.print("   ezractl scan")
    console.print("\n4. Start the agent:")
    console.print("   ezra-agent start")
    console.print("\n5. Or install as system service:")
    console.print("   ezractl install --service\n")


@app.command()
def init(
    companion_url: str = typer.Option(
        "http://localhost:3000", "--companion-url", help="Companion server URL",
    ),
    device_id: str | None = typer.Option(
        None, "--device-id", help="Device identifier",
    ),
    config_file: Path | None = _CONFIG_OPTION,
):
    """Initialize agent configuration."""
    config_manager = ConfigManager(config_file)

    # Create default config
    config = config_manager.create_default_config()
    config.companion_url = companion_url

    if device_id:
        config.device_id = device_id

    # Save configuration
    config_manager.config = config
    config_manager.save()

    console.print(f"✅ Configuration initialized at {config_manager.config_path}")
    console.print(f"📡 Companion URL: {config.companion_url}")
    console.print(f"🆔 Device ID: {config.device_id}")


@app.command()
def config(
    config_file: Path | None = _CONFIG_OPTION,
):
    """Show current configuration."""
    config_manager = ConfigManager(config_file)
    config = config_manager.load()

    table = Table(title="Agent Configuration")
    table.add_column("Setting", style="cyan")
    table.add_column("Value", style="green")

    table.add_row("Companion URL", config.companion_url)
    table.add_row("Device ID", config.device_id)
    table.add_row("Polling Interval", f"{config.polling_interval}ms")
    table.add_row("Max Retries", str(config.max_retries))
    table.add_row("Timeout", f"{config.timeout}ms")
    table.add_row("Log Level", config.log_level)
    table.add_row("Data Directory", str(config.data_dir))
    table.add_row("Cache Directory", str(config.cache_dir))
    table.add_row("Backup Directory", str(config.backup_dir))

    console.print(table)


@app.command()
def scan(
    config_file: Path | None = _CONFIG_OPTION,
):
    """Scan device information."""
    config_manager = ConfigManager(config_file)
    config = config_manager.load()

    scanner = DeviceScanner()
    device_info = scanner.scan(config.device_id)

    # Display device information
    console.print(Panel.fit("[bold]Device Information[/bold]\n", style="blue"))

    table = Table(title="Device Details")
    table.add_column("Property", style="cyan")
    table.add_column("Value", style="green")

    table.add_row("ID", device_info.id)
    table.add_row("Platform", device_info.platform)
    table.add_row("OS", f"{device_info.os} {device_info.version}")
    table.add_row("Architecture", device_info.architecture)
    table.add_row("CPU", device_info.hardware.cpu)
    table.add_row("Memory", f"{device_info.hardware.memory // (1024**3)} GB")
    table.add_row("Storage", f"{device_info.hardware.storage // (1024**3)} GB")
    if device_info.hardware.gpu:
        table.add_row("GPU", device_info.hardware.gpu)

    console.print(table)

    # Display capabilities
    if device_info.capabilities:
        console.print("\n[bold]Capabilities:[/bold]")
        for capability in device_info.capabilities:
            console.print(f"  • {capability}")


@app.command()
def test(
    config_file: Path | None = None,
):
    """Test connection to companion server."""
    config_manager = ConfigManager(config_file)
    config = config_manager.load()

    client = CompanionClient(config)

    console.print("🔍 Testing companion server connection...")

    # Health check
    if client.health_check():
        console.print("✅ Companion server is healthy")
    else:
        console.print("❌ Companion server is not available")
        return

    # Get providers status
    providers = client.get_providers_status()
    if providers:
        console.print("\n📡 LLM Providers:")
        for provider in providers.get("providers", []):
            status = "✅" if provider.get("available") else "❌"
            console.print(f"  {status} {provider.get('name')}")

    # Get public key
    public_key = client.get_public_key()
    if public_key:
        console.print(f"\n🔑 Public Key: {public_key[:32]}...")


@app.command()
def install(
    service: bool = typer.Option(False, "--service", help="Install as system service"),
):
    """Install agent as system service."""
    if not service:
        console.print("Use --service flag to install as system service")
        return

    # This would be implemented based on the platform
    console.print("🔧 Installing agent as system service...")

    if sys.platform == "linux":
        # Create systemd service file
        service_content = f"""[Unit]
Description=Ezra Agent
After=network.target

[Service]
Type=simple
User=ezra
WorkingDirectory={Path.home() / '.ezra'}
ExecStart=/usr/local/bin/ezra-agent start --daemon
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

        service_file = Path("/etc/systemd/system/ezra-agent.service")
        console.print(f"📝 Creating service file: {service_file}")
        console.print("Service content:")
        console.print(service_content)
        # Note: This would require sudo privileges
        console.print("⚠️  Run with sudo to install system service")

    elif sys.platform == "win32":
        # Create Windows service
        console.print("📝 Creating Windows service...")
        console.print("⚠️  Windows service installation not yet implemented")

    else:
        console.print("❌ Service installation not supported on this platform")


if __name__ == "__main__":
    app()
