name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        python-version: [3.11, 3.12]
        go-version: [1.21, 1.22]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: bootstrap/go.sum
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: |
        # Install workspace dependencies
        pnpm install
        
        # Install Python dependencies
        cd agent && pip install -e .
        cd ../executor && pip install -e .
    
    - name: Run TypeScript tests
      run: |
        cd companion
        pnpm test
    
    - name: Run Python tests
      run: |
        cd agent
        python -m pytest
        cd ../executor
        python -m pytest
    
    - name: Run Go tests
      run: |
        cd bootstrap
        go test ./...
    
    - name: Lint TypeScript
      run: |
        cd companion
        pnpm lint
    
    - name: Lint Python
      run: |
        cd agent
        python -m ruff check .
        cd ../executor
        python -m ruff check .
    
    - name: Lint Go
      run: |
        cd bootstrap
        golangci-lint run

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        cache: true
        cache-dependency-path: bootstrap/go.sum
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: |
        pnpm install
        cd agent && pip install -e .
        cd ../executor && pip install -e .
    
    - name: Build companion server
      run: |
        cd companion
        pnpm build
    
    - name: Build agent
      run: |
        cd agent
        python -m build
    
    - name: Build executor
      run: |
        cd executor
        python -m build
    
    - name: Build bootstrap
      run: |
        cd bootstrap
        make build-all
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          companion/dist/
          agent/dist/
          executor/dist/
          bootstrap/dist/
